FROM nginx:alpine
LABEL author="Darren Evans"
COPY ./dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
ENTRYPOINT ["nginx", "-g", "daemon off"]

server {
	listen 80;
	location / {
	 root /usr/share/nginx/html;
	 index index.html;
	 try_files $uri $uri/ /index.html =404;
	}
}
