kind: PersistentVolume
apiVersion: v1
metadata:
  name: app-config
spec:
  storageClassName: default
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/config"